### PR TITLE
Docs/201 new running app locally documentation

### PR DESCRIPTION
**Pull request by AleksandrMolchagin**
**Description**
Added documentation on how to get started with the CodeBuilder to run the Mule app locally (in the cloud).

### CODE REVIEW

**Comment by TharunKumarReddyPolu** [comment]
I see, It should be **Mule › Runtime: Default Arguments** instead of Mule: Runtime Arguments. Everything else looks good to me. Thanks for your efforts on this!

**Review by TharunKumarReddyPolu — CHANGES_REQUESTED** [review]
It should be **Mule › Runtime: Default Arguments** instead of Mule: Runtime Arguments

**Comment by AleksandrMolchagin** [comment]
@TharunKumarReddyPolu, I have made the changes based on your review. Could you please re-review it when you have time? Thanks!

**Review by TharunKumarReddyPolu — APPROVED** [review]
This looks good now! Thanks @AleksandrMolchagin :)

**Pull request merged**
