### PR TITLE
Fix/210 Handle Wrong Phone Number Input

### PR DESCRIPTION
**Pull request by TharunKumarReddyPolu**
Description:
Updated the `/searchByPhoneNumber` endpoint's query parameter `phoneNumber` to check for the pattern `'^\+?[1-9]\d{1,14}$'` which is E.164 international phone number format. 

If it is not in the pattern, The API responds with the status `400 Bad Request` as shown below in the screenshots of tests. 

- [X] Update the flow endpoint in the RAML file `src/main/resources/api/salesforce-data-api.raml`
- [x] Document the changes to the RAML file in `docs/raml_changes`
- [ ] ~~Update the flow in the related `.xml` file~~
- [ ] ~~Update the flow into the Postman collection~~
- [X] Test the new flow locally using Postman or Thunder (for testing, don't forget to point to local RAML in `src/main/mule/global.xml`: `api="salesforce-data-api.raml"`). 
- [X] Push the changes and create a [pull request (PR)](write_pull_request.md)
- [x] When merging, update the RAML file in [Exchange](https://anypoint.mulesoft.com/exchange/6c091e72-50d1-49ac-b04d-ee5bb9bc9dbd/salesforce-data-api/)

### RAML Specification:
```
/searchByPhoneNumber:
    get:
      displayName: Get matching contacts for a given phone number
      description: Get contacts matching a search string with a phone number (to be used for Student contacts for now)
      queryParameters:
        phoneNumber:
          displayName: phoneNumber
          description: Phone number
          type: string
          required: true
          pattern: '^\+?[1-9]\d{1,14}$'  # E.164 international phone number format
      responses:
        200:
          body:
            application/json:
              type: types.Contact[]
        400:
          body:
            application/json:
              example:
                message: Invalid phone number format. The phone number must be in E.164 format.
```

### Test Example:
`{{base_url}}/contacts/searchByPhoneNumber?phoneNumber=2287128B`
`{{base_url}}/contacts/searchByPhoneNumber?phoneNumber=269A`

### Screenshots of Tests:
image

image

### CODE REVIEW

**Comment by CritiqalPete** [comment]
Thanks. Assume if the handler can't resolve a bad number then it would also include a reason in the response "unable to parse phone number"
That said I'm not sure if this would make it back to the client. Would be nice to test.

**Comment by AleksandrMolchagin** [comment]
> Thanks. Assume if the handler can't resolve a bad number then it would also include a reason in the response "unable to parse phone number" That said I'm not sure if this would make it back to the client. Would be nice to test.

The message will be returned to the client once we have the new proxy. However, the error message is intended for front-end developers. We think it's better to send 'Unable to parse phone number' from the front-end whenever we get 400 code. This way we save more information to analyze any possible problems.

**Comment by AleksandrMolchagin** [comment]
@TharunKumarReddyPolu, I added your updated RAML specification to our next release - 4.0.4

**Comment by AleksandrMolchagin** [comment]
@TharunKumarReddyPolu Could you delete changes you made to the `pom.xml` file?

**Comment by TharunKumarReddyPolu** [comment]
@AleksandrMolchagin I have deleted the changes I made to `pom.xml` file and made the commit.

**Comment by CritiqalPete** [comment]
another note: Presently the Coach Mobile App tells users "numbers only no dashes, etc." A would presume this doesn't change that compatibility but would be good to test this with that in mind.

**Review by AleksandrMolchagin — APPROVED** [review]

**Pull request merged**
